# -*- coding: utf-8 -*-
"""endpoints.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tFYkNd9SaLyyGTaaC3BeQ85oF2vGs-TC

Dummy Functions to Imitate the Functions in the Gescam Notebook
"""

import io
import cv2
import numpy as np
import base64
import os
import uuid
from PIL import Image

# Dummy storage for uploaded frames
uploads = {}

def image_to_frame(image_data):
    image_stream = io.BytesIO(image_data)
    image = Image.open(image_stream)
    frame = cv2.cvtColor(np.array(image), cv2.COLOR_RGB2BGR)
    return [frame]

def video_to_frames(video_data):
    video_stream = io.BytesIO(video_data)
    temp_path = f"/tmp/upload_{uuid.uuid4()}.mp4"
    with open(temp_path, 'wb') as f:
        f.write(video_data)
    cap = cv2.VideoCapture(temp_path)
    if not cap.isOpened():
        os.remove(temp_path)
        raise ValueError("Failed to open video")
    frames = []
    frame_count = 0
    while cap.isOpened():
        ret, frame = cap.read()
        if not ret:
            break
        frame_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        frames.append(frame_rgb)
        frame_count += 1
    cap.release()
    os.remove(temp_path)
    print(f"Extracted {frame_count} frames from video")
    return frames

class Backend_send_frames:
    def __init__(self):
        pass

    def send_frames(self, virtual_path):
        # This is where your team member would process the virtual path
        # analysis_result = YourTeamMemberClass.process_path(virtual_path)  # Commented out for dummy data
        # For now, return None as a placeholder
        return None

def process_upload(file_data, content_type):
    # Determine file extension based on content type
    if 'image' in content_type:
        ext = '.png' if 'png' in content_type else '.jpg'
        frames = image_to_frame(file_data)
    elif 'video' in content_type:
        ext = '.mp4'
        frames = video_to_frames(file_data)
    else:
        raise ValueError("Unsupported content type")

    # Save the file to a temporary virtual path
    virtual_path = f"/tmp/upload_{uuid.uuid4()}{ext}"
    with open(virtual_path, 'wb') as f:
        f.write(file_data)

    backend = Backend_send_frames()
    # Call the backend with the virtual path
    # This is where your team member would process the virtual path
    # analysis_result = backend.send_frames(virtual_path)  # Commented out for dummy data

    # Dummy data matching the structure of test_results.json
    result = {
        "frame_data": []
    }
    # Simulate 4 frames (0, 1, 2, 8) as per test_results.json
    frame_indices = [0, 1, 2, 8]
    test_data = {
        0: {
            "mean_attention": 0.1252141764476059,
            "most_attended_object": "Desk/Table",
            "heatmap": "output/attention_test_results/frame_0_attention.png",
            "individuals": [
                {"person_idx": 0, "score": 0.10448516856413334, "looking_at": "Person/Teacher"},
                {"person_idx": 1, "score": 0.13387828138402252, "looking_at": "Desk/Table"},
                {"person_idx": 2, "score": 0.1560465225193184, "looking_at": "Desk/Table"},
                {"person_idx": 3, "score": 0.15807237264962165, "looking_at": "Person/Teacher"},
                {"person_idx": 4, "score": 0.18349290074547753, "looking_at": "Desk/Table"},
                {"person_idx": 5, "score": 0.10721112003448069, "looking_at": "Desk/Table"},
                {"person_idx": 6, "score": 0.10387236916576512, "looking_at": "Desk/Table"},
                {"person_idx": 7, "score": 0.06783428795315558, "looking_at": "Person/Teacher"},
                {"person_idx": 8, "score": 0.10366232143132947, "looking_at": "Desk/Table"},
                {"person_idx": 9, "score": 0.11394458244467387, "looking_at": "Desk/Table"},
                {"person_idx": 10, "score": 0.1562006901116547, "looking_at": "Desk/Table"},
                {"person_idx": 11, "score": 0.11291423647599003, "looking_at": "Desk/Table"},
                {"person_idx": 12, "score": 0.1261694403392539, "looking_at": "Desk/Table"},
            ]
        },
        1: {
            "mean_attention": 0.1254738093868792,
            "most_attended_object": "Desk/Table",
            "heatmap": "output/attention_test_results/frame_1_attention.png",
            "individuals": [
                {"person_idx": 0, "score": 0.10942332298436667, "looking_at": "Person/Teacher"},
                {"person_idx": 1, "score": 0.13388253754492327, "looking_at": "Desk/Table"},
                {"person_idx": 2, "score": 0.15608554775408268, "looking_at": "Desk/Table"},
                {"person_idx": 3, "score": 0.1561380539314996, "looking_at": "Person/Teacher"},
                {"person_idx": 4, "score": 0.1834726315275475, "looking_at": "Desk/Table"},
                {"person_idx": 5, "score": 0.10723141208291054, "looking_at": "Desk/Table"},
                {"person_idx": 6, "score": 0.10399976241169498, "looking_at": "Desk/Table"},
                {"person_idx": 7, "score": 0.06780224209069274, "looking_at": "Person/Teacher"},
                {"person_idx": 8, "score": 0.10394113548099995, "looking_at": "Desk/Table"},
                {"person_idx": 9, "score": 0.1140088565152837, "looking_at": "Desk/Table"},
                {"person_idx": 10, "score": 0.15620206144913026, "looking_at": "Desk/Table"},
                {"person_idx": 11, "score": 0.11291548882436474, "looking_at": "Desk/Table"},
                {"person_idx": 12, "score": 0.12605646943193277, "looking_at": "Desk/Table"},
            ]
        },
        2: {
            "mean_attention": 0.12396571152511779,
            "most_attended_object": "Desk/Table",
            "heatmap": "output/attention_test_results/frame_2_attention.png",
            "individuals": [
                {"person_idx": 0, "score": 0.09527363253582735, "looking_at": "Person/Teacher"},
                {"person_idx": 1, "score": 0.14836921339483525, "looking_at": "Desk/Table"},
                {"person_idx": 2, "score": 0.14436411217739076, "looking_at": "Desk/Table"},
                {"person_idx": 3, "score": 0.15349900196815722, "looking_at": "Person/Teacher"},
                {"person_idx": 4, "score": 0.18445737866350095, "looking_at": "Person/Teacher"},
                {"person_idx": 5, "score": 0.10572777898487402, "looking_at": "Desk/Table"},
                {"person_idx": 6, "score": 0.10707686369569275, "looking_at": "Desk/Table"},
                {"person_idx": 7, "score": 0.06356598739366746, "looking_at": "Person/Teacher"},
                {"person_idx": 8, "score": 0.10007282708538696, "looking_at": "Desk/Table"},
                {"person_idx": 9, "score": 0.11294816094741689, "looking_at": "Desk/Table"},
                {"person_idx": 10, "score": 0.15548095727272085, "looking_at": "Desk/Table"},
                {"person_idx": 11, "score": 0.11195930565554589, "looking_at": "Desk/Table"},
                {"person_idx": 12, "score": 0.12875903005151487, "looking_at": "Desk/Table"},
            ]
        },
        8: {
            "mean_attention": 0.12139347740718362,
            "most_attended_object": "Desk/Table",
            "heatmap": "output/attention_test_results/frame_8_attention.png",
            "individuals": [
                {"person_idx": 0, "score": 0.09078574274899437, "looking_at": "Person/Teacher"},
                {"person_idx": 1, "score": 0.12345824152398564, "looking_at": "Desk/Table"},
                {"person_idx": 2, "score": 0.15128009983636728, "looking_at": "Desk/Table"},
                {"person_idx": 3, "score": 0.13927395239516044, "looking_at": "Person/Teacher"},
                {"person_idx": 4, "score": 0.1786989535419707, "looking_at": "Person/Teacher"},
                {"person_idx": 5, "score": 0.10607147876289673, "looking_at": "Desk/Table"},
                {"person_idx": 6, "score": 0.09540428769832941, "looking_at": "Desk/Table"},
                {"person_idx": 7, "score": 0.06263289974158397, "looking_at": "Person/Teacher"},
                {"person_idx": 8, "score": 0.1125039989768993, "looking_at": "Desk/Table"},
                {"person_idx": 9, "score": 0.131745218244032, "looking_at": "Desk/Table"},
                {"person_idx": 10, "score": 0.1639194555486938, "looking_at": "Desk/Table"},
                {"person_idx": 11, "score": 0.11632965674252772, "looking_at": "Desk/Table"},
                {"person_idx": 12, "score": 0.10601122053194557, "looking_at": "Desk/Table"},
            ]
        }
    }

    # Adjust the number of frames to match input if necessary, but here we use all 4 frames
    for idx, frame in enumerate(frames):
        frame_idx = frame_indices[idx % len(frame_indices)]  # Cycle through 0, 1, 2, 8
        frame_data = test_data[frame_idx]
        # Convert frame to base64 for storage
        _, buffer = cv2.imencode('.jpg', frame)
        frame_base64 = base64.b64encode(buffer).decode('utf-8')

        # Format individual scores
        individual_scores = [
            {
                "person_idx": person["person_idx"],
                "attention_score": person["score"],
                "looking_at": person["looking_at"]
            }
            for person in frame_data["individuals"]
        ]

        # Format attention data
        attention_data = {
            "frame_stats": {
                "mean_attention": frame_data["mean_attention"],
                "most_attended_object": frame_data["most_attended_object"],
                "timestamp": idx
            },
            "individual_scores": individual_scores
        }

        # Dummy heatmap and engagement visualizations (as paths for now, since frontend expects strings)
        heatmap_data = frame_data["heatmap"]
        engagement_data = "Engagement level: " + ("High" if frame_data["mean_attention"] > 0.5 else "Low")

        frame_result = {
            "frame_id": idx,
            "attention_data": attention_data,
            "original_frame": frame_base64,
            "visualizations": {
                "heatmap": heatmap_data,
                "engagement": engagement_data
            }
        }
        result["frame_data"].append(frame_result)

    # Clean up the temporary file
    if os.path.exists(virtual_path):
        os.remove(virtual_path)

    return result

"""Endpoints that app.py will use

All endpoints are POST functions

*   /upload_frame - is used to upload a frame for analysis
*   /analyze_frame - returns the analysis results the model generates
*   /analyze_temporal - returns analyzed results
*   /visualize_frame - returns the path to the visualization
*   /get_frame - returns the original frame for display
"""

# Kill any running ngrok process first
!pkill ngrok
!pip install flask pyngrok
from pyngrok import ngrok
!ngrok authtoken 207Efj2NVQAgP1LM7aqMDL7AKkW_6T4MTzNgKcpZiZQEcBzAn

from flask import Flask, request, jsonify
import uuid

app = Flask(__name__)

# Storage for processed frames (in memory)
uploads = {}  # {upload_id: {"frame_data": [...]}

# Endpoint: Upload image or video
@app.route('/upload_frame', methods=['POST'])
def upload_frame():
    print("Received request at /upload_frame")
    if 'file' not in request.files:
        print("Error: No file part in request")
        return jsonify({"error": "No file part"}), 400

    file = request.files['file']
    if file.filename == '':
        print("Error: No selected file")
        return jsonify({"error": "No selected file"}), 400

    try:
        print(f"Processing file: {file.filename}, content_type: {file.content_type}")
        file_data = file.read()
        upload_id = str(uuid.uuid4())
        analysis_result = process_upload(file_data, file.content_type)

        # Store the results in memory
        uploads[upload_id] = analysis_result
        response = {"upload_id": upload_id, "frame_count": len(analysis_result["frame_data"])}
        print(f"Upload successful, response: {response}")
        return jsonify(response), 200
    except Exception as e:
        print(f"Error in /upload_frame: {str(e)}")
        return jsonify({"error": str(e)}), 500

# Endpoint: Get original frame for Raw Feed
@app.route('/get_frame', methods=['POST'])
def get_frame():
    print("Received request at /get_frame")
    data = request.get_json()
    if not data or 'upload_id' not in data or 'frame_idx' not in data:
        print("Error: Missing upload_id or frame_idx")
        return jsonify({"error": "Missing upload_id or frame_idx"}), 400

    upload_id = data['upload_id']
    frame_idx = data['frame_idx']

    if upload_id not in uploads:
        print(f"Error: Upload ID {upload_id} not found")
        return jsonify({"error": "Upload ID not found"}), 404

    analysis = uploads[upload_id]
    frame_data = next((frame for frame in analysis["frame_data"] if frame["frame_id"] == frame_idx), None)
    if frame_data is None:
        print(f"Error: Frame {frame_idx} not found for upload_id {upload_id}")
        return jsonify({"error": "Frame not found"}), 404

    # Return the original frame as base64
    response = {
        "frame_idx": frame_idx,
        "original_frame": frame_data["original_frame"]
    }
    print(f"Returning frame: {response}")
    return jsonify(response)

# Endpoint: Analyze a specific frame
@app.route('/analyze_frame', methods=['POST'])
def analyze_frame():
    print("Received request at /analyze_frame")
    data = request.get_json()
    if not data or 'upload_id' not in data or 'frame_idx' not in data:
        print("Error: Missing upload_id or frame_idx")
        return jsonify({"error": "Missing upload_id or frame_idx"}), 400

    upload_id = data['upload_id']
    frame_idx = data['frame_idx']

    if upload_id not in uploads:
        print(f"Error: Upload ID {upload_id} not found")
        return jsonify({"error": "Upload ID not found"}), 404

    analysis = uploads[upload_id]
    frame_data = next((frame for frame in analysis["frame_data"] if frame["frame_id"] == frame_idx), None)
    if frame_data is None:
        print(f"Error: Frame {frame_idx} not found for upload_id {upload_id}")
        return jsonify({"error": "Frame not found"}), 404

    # Return the attention data for this frame
    response = frame_data["attention_data"]
    print(f"Returning attention data: {response}")
    return jsonify(response)

# Endpoint: Analyze temporal data (trend across frames)
@app.route('/analyze_temporal', methods=['POST'])
def analyze_temporal():
    print("Received request at /analyze_temporal")
    data = request.get_json()
    if not data or 'upload_id' not in data:
        print("Error: Missing upload_id")
        return jsonify({"error": "Missing upload_id"}), 400

    upload_id = data['upload_id']
    if upload_id not in uploads:
        print(f"Error: Upload ID {upload_id} not found")
        return jsonify({"error": "Upload ID not found"}), 404

    analysis = uploads[upload_id]
    trend = [
        {
            "frame_idx": frame["frame_id"],
            "mean_attention": frame["attention_data"]["frame_stats"]["mean_attention"],
            "timestamp": frame["attention_data"]["frame_stats"]["timestamp"]
        }
        for frame in analysis["frame_data"]
    ]
    response = {"upload_id": upload_id, "trend": trend}
    print(f"Returning temporal analysis: {response}")
    return jsonify(response)

# Endpoint: Visualize a specific frame (Heatmap or Engagement)
@app.route('/visualize_frame', methods=['POST'])
def visualize_frame():
    print("Received request at /visualize_frame")
    data = request.get_json()
    if not data or 'upload_id' not in data or 'frame_idx' not in data or 'vis_type' not in data:
        print("Error: Missing upload_id, frame_idx, or vis_type")
        return jsonify({"error": "Missing upload_id, frame_idx, or vis_type"}), 400

    upload_id = data['upload_id']
    frame_idx = data['frame_idx']
    vis_type = data['vis_type']

    if upload_id not in uploads:
        print(f"Error: Upload ID {upload_id} not found")
        return jsonify({"error": "Upload ID not found"}), 404

    analysis = uploads[upload_id]
    frame_data = next((frame for frame in analysis["frame_data"] if frame["frame_id"] == frame_idx), None)
    if frame_data is None:
        print(f"Error: Frame {frame_idx} not found for upload_id {upload_id}")
        return jsonify({"error": "Frame not found"}), 404

    # Return the pre-generated visualization as a string (path or description)
    if vis_type not in frame_data["visualizations"]:
        print(f"Error: Invalid vis_type {vis_type}")
        return jsonify({"error": "Invalid vis_type"}), 400

    response = {
        "frame_idx": frame_idx,
        "vis_type": vis_type,
        "vis_image": frame_data["visualizations"][vis_type]
    }
    print(f"Returning visualization: {response}")
    return jsonify(response)

# Start Flask with ngrok
public_url = ngrok.connect(5000).public_url
print(f" * ngrok tunnel: {public_url}")
app.run(host="0.0.0.0", port=5000)